import Foundation

struct Product: Identifiable {
    var id = UUID()
    var productName: String
    var image: String
    var price: Int
    var description: String
}

var productList = [
    Product(productName: "Milk", image: "milk", price: 2, description: "Milk is a nutrient-rich liquid food produced by the mammary glands of mammals. It is the primary source of nutrition for young mammals (including breastfed human infants) before they are able to digest solid food. Early-lactation milk, which is called colostrum, contains antibodies that strengthen the immune system, and thus reduces the risk of many diseases. Milk contains many other nutrients, including protein and lactose."),
    Product(productName: "Bread", image: "bread", price: 1, description: "Bread is a staple food prepared from a dough of flour (usually wheat) and water, usually by baking. Throughout recorded history and around the world, it has been an important part of many cultures' diet. It is one of the oldest human-made foods, having been of significance since the dawn of agriculture, and plays an essential role in both religious rituals and secular culture."),
    Product(productName: "Blue cheese", image: "blue-cheese", price: 5, description: "Blue cheese (or bleu cheese) is semi-soft cheese with a sharp, salty flavor. It is made with cultures of the edible mold Penicillium, giving it spots or veins throughout the cheese in shades of blue or green. It carries a distinct smell, either from the mold or from various specially cultivated bacteria such as Brevibacterium linens, which also causes foot odor and other human body odors. Some blue cheeses are injected with spores before the curds form, and others have spores mixed in with the curds after they form. Blue cheeses are typically aged in temperature-controlled environments such as caves. Blue cheese can be eaten by itself or can be spread, crumbled or melted into or over many other foods."),
    Product(productName: "Ice Cream", image: "ice-cream", price: 3, description: "Ice cream is a sweetened frozen food typically eaten as a snack or dessert. It may be made from milk or cream and is flavoured with a sweetener, either sugar or an alternative, and a spice, such as cocoa or vanilla, or with fruit such as strawberries or peaches. It can also be made by whisking a flavored cream base and liquid nitrogen together. Food coloring is sometimes added, in addition to stabilizers. The mixture is cooled below the freezing point of water and stirred to incorporate air spaces and to prevent detectable ice crystals from forming. The result is a smooth, semi-solid foam that is solid at very low temperatures (below 2 °C or 35 °F). It becomes more malleable as its temperature increases."),
    Product(productName: "Steak", image: "steak", price: 15, description: "A steak, also sometimes called 'beef steak', is a meat generally sliced across the muscle fibers, potentially including a bone. It is normally grilled, though it can also be pan-fried. Steak can also be cooked in sauce, such as in steak and kidney pie, or minced and formed into patties, such as hamburgers. Besides cattle, steaks are also often cut from other animals, including bison, camel, goat, horse, kangaroo, sheep, ostrich, pigs, reindeer, turkey, deer, and zebu, as well as various types of fish, especially salmon and large fish such as swordfish, shark, and marlin. For some meats, such as pork, lamb and mutton, chevon, and veal, these cuts are often referred to as chops. Some cured meat, such as gammon, is commonly served as steak."),
    Product(productName: "Chicken", image: "raw-chicken", price: 5, description: "The chicken (Gallus domesticus) is a domesticated subspecies of the red junglefowl, with attributes of wild species such as grey and ceylon junglefowl that are originally from Southeastern Asia. Rooster or cock is a term for an adult male bird, and a younger male may be called a cockerel. A male that has been castrated is a capon. An adult female bird is called a hen and a sexually immature female is called a pullet. Originally raised for cockfighting or for special ceremonies, chickens were not kept for food until the Hellenistic period (4th–2nd centuries BC). Humans now keep chickens primarily as a source of food (consuming both their meat and eggs) and as pets."),
    Product(productName: "Strawberry", image: "strawberries", price: 4, description: "The garden strawberry (or simply strawberry; Fragaria × ananassa) is a widely grown hybrid species of the genus Fragaria, collectively known as the strawberries, which are cultivated worldwide for their fruit. The fruit is widely appreciated for its characteristic aroma, bright red color, juicy texture, and sweetness. It is consumed in large quantities, either fresh or in such prepared foods as jam, juice, pies, ice cream, milkshakes, and chocolates. Artificial strawberry flavorings and aromas are also widely used in products such as candy, soap, lip gloss, perfume, and many others."),
    Product(productName: "Apple", image: "apple", price: 2, description: "An apple is an edible fruit produced by an apple tree (Malus domestica). Apple trees are cultivated worldwide and are the most widely grown species in the genus Malus. The tree originated in Central Asia, where its wild ancestor, Malus sieversii, is still found today. Apples have been grown for thousands of years in Asia and Europe and were brought to North America by European colonists. Apples have religious and mythological significance in many cultures, including Norse, Greek, and European Christian tradition.")
]
